3 - Add GameInfo Component
Team-Benedict/Scrambled-Eggs-Web pull request #5
Opened 2022-04-14 19:55 UTC by amontanooo

### Description

Created a component to hold information on what will be the given game.

### Proposed Changes
Added a component for game info that holds release date, publisher and developer.

### Resolves

resolves #3 

### Changes tested on

- [ ] Chrome

2022-04-19 17:49 UTC, amontanooo commented on frontend/src/App.scss
> +.App {
I haven't done anything to this, but will keep that in mind.

2022-04-20 02:16 UTC, ForkBombGIT commented on frontend/src/App.js
>      <div className="App">
The element should be self closing because it has no children:

`<div className="App" />`

2022-04-20 02:16 UTC, ForkBombGIT commented on frontend/src/Components/GameInfo/GameInfo.js
> +        <div className="game-info">
The component has a good starting point now. We can apply some basic styles to make the component a little more attractive.

This is how I styled mine, you can use it as a reference or design your own. 

<img width="299" alt="Screen Shot 2022-04-19 at 10 14 01 PM" src="https://user-images.githubusercontent.com/34588189/164133269-beb0b13c-69d1-4b03-8fd9-b04beb084507.png">

Note that the component should ideally be responsive between the viewpoints of 320px at a minimum.

Also, note the font differences in the screenshots. This is not because of explicit styling in the project, but rather the default markup of the elements

2022-04-20 02:16 UTC, ForkBombGIT commented on frontend/src/Components/GameInfo/GameInfo.js
> +GameInfo.propTypes = {
Ensure to update `propTypes` when you add new props.

2022-04-20 02:16 UTC, ForkBombGIT commented on frontend/src/Components/GameInfo/GameInfo.scss
> +.gameinfo{
This style currently doesn't do anything

2022-04-20 02:16 UTC, ForkBombGIT commented on frontend/src/Components/GameInfo/GameInfo.js
> +        <div className="game-info">
Ensure to use classes and ids appropriately when styling, I recommend using [bem](http://getbem.com/naming/) as it's worked for me in my other projects.

2022-04-20 02:16 UTC, ForkBombGIT commented on frontend/src/Components/GameInfo/GameInfo.js
> +function GameInfo ({date, publish, developer, title, platforms, genres}) {
In the below screenshot, notice the `unordered lists`. We should update those fields to expect arrays instead of strings and handle/render them appropriately.

2022-04-20 02:18 UTC, ForkBombGIT commented on frontend/src/Components/GameInfo/GameInfo.js
> +        <div className="game-info">
Notice the `unordered lists`. We should update the corresponding props to expect arrays instead of strings and render them appropriately.

2022-05-10 11:42 UTC, ForkBombGIT requested changes

2022-05-10 11:42 UTC, ForkBombGIT commented on frontend/public/index.html
>  <!DOCTYPE html>
Did we need any of the changes made in here? Seems like you changed the formatting in here, but the only thing we should be changing in here is metadata like `description` and `title`. We can talk more about what metadata does offline.

2022-05-10 11:42 UTC, ForkBombGIT commented on frontend/src/Components/GameInfo/GameInfo.js
> +    PropTypes.oneOfType([PropTypes.number, PropTypes.string])
Why did you choose to include the number `prop-type`? Think about what data is passed in, I doubt it would ever need to accept a number.

2022-05-10 11:42 UTC, ForkBombGIT commented on frontend/src/App.js
> +      <GameInfo
Let's not commit this, as it's just placeholder data.

2022-05-10 11:42 UTC, ForkBombGIT commented on frontend/src/Components/GameInfo/GameInfo.js
> +function GameInfo({ date, publish, developer, title, platforms, genres }) {
Let's have `genres` expect an array, rather than a string. It's typical for games to have several genres. Render it in the same way you did platforms.

2022-05-10 11:42 UTC, ForkBombGIT commented on frontend/src/Components/GameInfo/GameInfo.js
> +    <div className="game-info">
So I previously mentioned the use of the [bem](http://getbem.com/introduction/) methodology, which stands for block-element-modifier, and this is the perfect place to start using it.

In this case, `game-info` is the block, and all the fields within are the elements. Following this methodology, class names should be structured as: `block__element--modifier`. So, we can write ``ttl` as `game-info__ttl`. Do try to use readable names when naming things (title vs ttl).

2022-05-10 11:42 UTC, ForkBombGIT commented on frontend/src/Components/GameInfo/GameInfo.scss
> +.game-info {
Using `bem` with `sass` we can write some real organized style sheets.

`sass` lets us nest styles:

```
.game-info {
    ...
    &__title {
        ...
   }
}
```

Two things to notice. First, the `&` operator essentially says "replace this operator with the name of the parent element", in this case, `game-info`. Additionally, having `game-info__title` nested within `game-info` says that ONLY style the `game-info__title` within `game-info`. 

The power of this is more visible when styling generic elements:

```
.game-info {
    ...
    h2 {
        ...
   }
}
```

2022-05-10 21:16 UTC, ForkBombGIT commented on frontend/public/index.html
> +</html>
Add EOF.

2022-05-10 21:16 UTC, ForkBombGIT commented on frontend/src/App.js
> +      <GameInfo />
Remove this component, we don't need it here yet.

2022-05-10 21:16 UTC, ForkBombGIT commented on frontend/src/Components/GameInfo/GameInfo.scss
> +}
Reminder!

2022-05-10 21:16 UTC, ForkBombGIT commented on frontend/.eslintrc.json
> +}
Add EOF.

2022-05-18 12:18 UTC, ForkBombGIT approved these changes
Looks good!

2022-11-14 14:09 UTC, merged